spring:
  application:
    name: "dog-portal-services"
  datasource:
    initialize: true
    url: jdbc:h2:mem:dogdb
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
